name: Generate Datas

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Gera a anima√ß√£o
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: guilhermeariel
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica no GitHub Pages (branch output)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "üêç Atualizando cobra do GitHub"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
